/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UcetRouteImport } from './routes/ucet'
import { Route as ProduktyRouteImport } from './routes/produkty'
import { Route as PrihlaseniRouteImport } from './routes/prihlaseni'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProduktIdRouteImport } from './routes/produkt.$id'
import { Route as AdminUzivateleRouteImport } from './routes/admin/uzivatele'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminNastaveniRouteImport } from './routes/admin/nastaveni'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAbraRouteImport } from './routes/admin/abra'

const UcetRoute = UcetRouteImport.update({
  id: '/ucet',
  path: '/ucet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyRoute = ProduktyRouteImport.update({
  id: '/produkty',
  path: '/produkty',
  getParentRoute: () => rootRouteImport,
} as any)
const PrihlaseniRoute = PrihlaseniRouteImport.update({
  id: '/prihlaseni',
  path: '/prihlaseni',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProduktIdRoute = ProduktIdRouteImport.update({
  id: '/produkt/$id',
  path: '/produkt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUzivateleRoute = AdminUzivateleRouteImport.update({
  id: '/uzivatele',
  path: '/uzivatele',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNastaveniRoute = AdminNastaveniRouteImport.update({
  id: '/nastaveni',
  path: '/nastaveni',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAbraRoute = AdminAbraRouteImport.update({
  id: '/abra',
  path: '/abra',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/o-nas': typeof ONasRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/produkty': typeof ProduktyRoute
  '/ucet': typeof UcetRoute
  '/admin/abra': typeof AdminAbraRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/nastaveni': typeof AdminNastaveniRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/uzivatele': typeof AdminUzivateleRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o-nas': typeof ONasRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/produkty': typeof ProduktyRoute
  '/ucet': typeof UcetRoute
  '/admin/abra': typeof AdminAbraRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/nastaveni': typeof AdminNastaveniRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/uzivatele': typeof AdminUzivateleRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/o-nas': typeof ONasRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/produkty': typeof ProduktyRoute
  '/ucet': typeof UcetRoute
  '/admin/abra': typeof AdminAbraRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/nastaveni': typeof AdminNastaveniRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/uzivatele': typeof AdminUzivateleRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/o-nas'
    | '/prihlaseni'
    | '/produkty'
    | '/ucet'
    | '/admin/abra'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/nastaveni'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/uzivatele'
    | '/produkt/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/o-nas'
    | '/prihlaseni'
    | '/produkty'
    | '/ucet'
    | '/admin/abra'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/nastaveni'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/uzivatele'
    | '/produkt/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/o-nas'
    | '/prihlaseni'
    | '/produkty'
    | '/ucet'
    | '/admin/abra'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/nastaveni'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/uzivatele'
    | '/produkt/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ONasRoute: typeof ONasRoute
  PrihlaseniRoute: typeof PrihlaseniRoute
  ProduktyRoute: typeof ProduktyRoute
  UcetRoute: typeof UcetRoute
  ProduktIdRoute: typeof ProduktIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ucet': {
      id: '/ucet'
      path: '/ucet'
      fullPath: '/ucet'
      preLoaderRoute: typeof UcetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty': {
      id: '/produkty'
      path: '/produkty'
      fullPath: '/produkty'
      preLoaderRoute: typeof ProduktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prihlaseni': {
      id: '/prihlaseni'
      path: '/prihlaseni'
      fullPath: '/prihlaseni'
      preLoaderRoute: typeof PrihlaseniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/produkt/$id': {
      id: '/produkt/$id'
      path: '/produkt/$id'
      fullPath: '/produkt/$id'
      preLoaderRoute: typeof ProduktIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uzivatele': {
      id: '/admin/uzivatele'
      path: '/uzivatele'
      fullPath: '/admin/uzivatele'
      preLoaderRoute: typeof AdminUzivateleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nastaveni': {
      id: '/admin/nastaveni'
      path: '/nastaveni'
      fullPath: '/admin/nastaveni'
      preLoaderRoute: typeof AdminNastaveniRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/abra': {
      id: '/admin/abra'
      path: '/abra'
      fullPath: '/admin/abra'
      preLoaderRoute: typeof AdminAbraRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAbraRoute: typeof AdminAbraRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminNastaveniRoute: typeof AdminNastaveniRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUzivateleRoute: typeof AdminUzivateleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAbraRoute: AdminAbraRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminNastaveniRoute: AdminNastaveniRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUzivateleRoute: AdminUzivateleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ONasRoute: ONasRoute,
  PrihlaseniRoute: PrihlaseniRoute,
  ProduktyRoute: ProduktyRoute,
  UcetRoute: UcetRoute,
  ProduktIdRoute: ProduktIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
